# -*- coding: utf-8 -*-

from PySide2 import QtCore, QtGui, QtWidgets
from AlphaZeroGUI import IMAGE_DIR


class Ui_DialogEditArgs(QtWidgets.QDialog):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)

    def setupUi(self, DialogNewArgs):
        DialogNewArgs.setObjectName("DialogNewArgs")
        DialogNewArgs.resize(540, 670)
        self.btnBoxSave = QtWidgets.QDialogButtonBox(DialogNewArgs)
        self.btnBoxSave.setGeometry(QtCore.QRect(370, 640, 156, 23))
        self.btnBoxSave.setOrientation(QtCore.Qt.Horizontal)
        self.btnBoxSave.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnBoxSave.setObjectName("btnBoxSave")
        self.lblTitle = QtWidgets.QLabel(DialogNewArgs)
        self.lblTitle.setGeometry(QtCore.QRect(10, 10, 401, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.tableArgs = QtWidgets.QTableWidget(DialogNewArgs)
        self.tableArgs.setGeometry(QtCore.QRect(10, 50, 521, 581))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tableArgs.setFont(font)
        self.tableArgs.setLineWidth(1)
        self.tableArgs.setAutoScroll(False)
        self.tableArgs.setShowGrid(True)
        self.tableArgs.setWordWrap(False)
        self.tableArgs.setColumnCount(1)
        self.tableArgs.setObjectName("tableArgs")
        self.tableArgs.horizontalHeader().setVisible(False)
        self.tableArgs.verticalHeader().setVisible(True)
        self.tableArgs.verticalHeader().setCascadingSectionResizes(False)
        self.tableArgs.verticalHeader().setDefaultSectionSize(30)
        self.tableArgs.verticalHeader().setHighlightSections(True)
        self.tableArgs.verticalHeader().setSortIndicatorShown(False)
        self.checkLoadArgs = QtWidgets.QCheckBox(DialogNewArgs)
        self.checkLoadArgs.setGeometry(QtCore.QRect(10, 640, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkLoadArgs.setFont(font)
        self.checkLoadArgs.setChecked(True)
        self.checkLoadArgs.setObjectName("checkLoadArgs")
        self.btnResetArgs = QtWidgets.QPushButton(DialogNewArgs)
        self.btnResetArgs.setGeometry(QtCore.QRect(414, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnResetArgs.setFont(font)
        self.btnResetArgs.setObjectName("btnResetArgs")

        self.retranslateUi(DialogNewArgs)
        self.btnBoxSave.accepted.connect(DialogNewArgs.accept)
        self.btnBoxSave.rejected.connect(DialogNewArgs.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogNewArgs)

    def retranslateUi(self, DialogNewArgs):
        _translate = QtCore.QCoreApplication.translate
        DialogNewArgs.setWindowTitle(_translate("DialogNewArgs", "New Arguments Editor"))
        self.lblTitle.setText(_translate("DialogNewArgs", "Edit args from current run below, and press OK to save them."))
        self.tableArgs.setSortingEnabled(True)
        self.checkLoadArgs.setText(_translate("DialogNewArgs", "Load these args into training menu"))
        self.btnResetArgs.setText(_translate("DialogNewArgs", "Reset To Default"))


class Ui_FormMainMenu(QtWidgets.QMainWindow):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setWindowFlags(QtCore.Qt.WindowMinimizeButtonHint | QtCore.Qt.WindowCloseButtonHint)
        self.setupUi(self)

    def setupUi(self, FormMainMenu):
        FormMainMenu.setObjectName("FormMainMenu")
        FormMainMenu.resize(876, 647)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FormMainMenu.sizePolicy().hasHeightForWidth())
        FormMainMenu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        FormMainMenu.setFont(font)
        self.frameTrain = QtWidgets.QFrame(FormMainMenu)
        self.frameTrain.setGeometry(QtCore.QRect(10, 60, 861, 581))
        self.frameTrain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTrain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTrain.setObjectName("frameTrain")
        self.lblCurrentRun = QtWidgets.QLabel(self.frameTrain)
        self.lblCurrentRun.setEnabled(True)
        self.lblCurrentRun.setGeometry(QtCore.QRect(386, 10, 400, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblCurrentRun.setFont(font)
        self.lblCurrentRun.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lblCurrentRun.setObjectName("lblCurrentRun")
        self.progressTotal = QtWidgets.QProgressBar(self.frameTrain)
        self.progressTotal.setGeometry(QtCore.QRect(430, 530, 381, 23))
        self.progressTotal.setProperty("value", 0)
        self.progressTotal.setObjectName("progressTotal")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frameTrain)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 20, 361, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layoutTrainStats = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layoutTrainStats.setContentsMargins(0, 0, 0, 0)
        self.layoutTrainStats.setSpacing(6)
        self.layoutTrainStats.setObjectName("layoutTrainStats")
        self.lblTrainStatsTitle = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblTrainStatsTitle.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblTrainStatsTitle.setFont(font)
        self.lblTrainStatsTitle.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lblTrainStatsTitle.setObjectName("lblTrainStatsTitle")
        self.layoutTrainStats.addWidget(self.lblTrainStatsTitle)
        self.lblStatus = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lblStatus.setFont(font)
        self.lblStatus.setObjectName("lblStatus")
        self.layoutTrainStats.addWidget(self.lblStatus)
        self.lblTrainIteration = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblTrainIteration.setFont(font)
        self.lblTrainIteration.setObjectName("lblTrainIteration")
        self.layoutTrainStats.addWidget(self.lblTrainIteration)
        self.lblTrainSelfPlayIter = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblTrainSelfPlayIter.setFont(font)
        self.lblTrainSelfPlayIter.setObjectName("lblTrainSelfPlayIter")
        self.layoutTrainStats.addWidget(self.lblTrainSelfPlayIter)
        self.lblTrainNumGames = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblTrainNumGames.setFont(font)
        self.lblTrainNumGames.setObjectName("lblTrainNumGames")
        self.layoutTrainStats.addWidget(self.lblTrainNumGames)
        self.lblTrainLossPolicy = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblTrainLossPolicy.setFont(font)
        self.lblTrainLossPolicy.setObjectName("lblTrainLossPolicy")
        self.layoutTrainStats.addWidget(self.lblTrainLossPolicy)
        self.lblTrainLossValue = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblTrainLossValue.setFont(font)
        self.lblTrainLossValue.setObjectName("lblTrainLossValue")
        self.layoutTrainStats.addWidget(self.lblTrainLossValue)
        self.lblTrainLossTotal = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblTrainLossTotal.setFont(font)
        self.lblTrainLossTotal.setObjectName("lblTrainLossTotal")
        self.layoutTrainStats.addWidget(self.lblTrainLossTotal)
        self.lblTrainEpsTime = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblTrainEpsTime.setFont(font)
        self.lblTrainEpsTime.setObjectName("lblTrainEpsTime")
        self.layoutTrainStats.addWidget(self.lblTrainEpsTime)
        self.lblTrainIterTime = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblTrainIterTime.setFont(font)
        self.lblTrainIterTime.setObjectName("lblTrainIterTime")
        self.layoutTrainStats.addWidget(self.lblTrainIterTime)
        self.lblTrainTimeRemaining = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblTrainTimeRemaining.setFont(font)
        self.lblTrainTimeRemaining.setObjectName("lblTrainTimeRemaining")
        self.layoutTrainStats.addWidget(self.lblTrainTimeRemaining)
        self.progressIteration = QtWidgets.QProgressBar(self.frameTrain)
        self.progressIteration.setGeometry(QtCore.QRect(430, 490, 381, 23))
        self.progressIteration.setProperty("value", 0)
        self.progressIteration.setInvertedAppearance(False)
        self.progressIteration.setObjectName("progressIteration")
        self.lblProgressIterTitle = QtWidgets.QLabel(self.frameTrain)
        self.lblProgressIterTitle.setGeometry(QtCore.QRect(350, 480, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblProgressIterTitle.setFont(font)
        self.lblProgressIterTitle.setObjectName("lblProgressIterTitle")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frameTrain)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(500, 80, 169, 301))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.layoutTrainButtons = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.layoutTrainButtons.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.layoutTrainButtons.setContentsMargins(0, 0, 0, 0)
        self.layoutTrainButtons.setSpacing(6)
        self.layoutTrainButtons.setObjectName("layoutTrainButtons")
        self.btnLoadTrainArgs = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnLoadTrainArgs.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnLoadTrainArgs.setFont(font)
        self.btnLoadTrainArgs.setAutoDefault(False)
        self.btnLoadTrainArgs.setFlat(False)
        self.btnLoadTrainArgs.setObjectName("btnLoadTrainArgs")
        self.layoutTrainButtons.addWidget(self.btnLoadTrainArgs)
        self.btnLoadTrainEnv = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnLoadTrainEnv.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnLoadTrainEnv.setFont(font)
        self.btnLoadTrainEnv.setObjectName("btnLoadTrainEnv")
        self.layoutTrainButtons.addWidget(self.btnLoadTrainEnv)
        self.btnEditTrainArgs = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnEditTrainArgs.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnEditTrainArgs.setFont(font)
        self.btnEditTrainArgs.setObjectName("btnEditTrainArgs")
        self.layoutTrainButtons.addWidget(self.btnEditTrainArgs)
        self.btnOpenTensorboard = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnOpenTensorboard.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnOpenTensorboard.setFont(font)
        self.btnOpenTensorboard.setObjectName("btnOpenTensorboard")
        self.layoutTrainButtons.addWidget(self.btnOpenTensorboard)
        self.btnRemoveArgs = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnRemoveArgs.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnRemoveArgs.setFont(font)
        self.btnRemoveArgs.setObjectName("btnRemoveArgs")
        self.layoutTrainButtons.addWidget(self.btnRemoveArgs)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frameTrain)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 480, 271, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.layoutTrainControls = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.layoutTrainControls.setContentsMargins(0, 0, 0, 0)
        self.layoutTrainControls.setObjectName("layoutTrainControls")
        self.btnTrainControlStart = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnTrainControlStart.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(str(IMAGE_DIR / "play.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnTrainControlStart.setIcon(icon)
        self.btnTrainControlStart.setIconSize(QtCore.QSize(32, 32))
        self.btnTrainControlStart.setFlat(True)
        self.btnTrainControlStart.setObjectName("btnTrainControlStart")
        self.layoutTrainControls.addWidget(self.btnTrainControlStart)
        self.btnTrainControlPause = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnTrainControlPause.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(str(IMAGE_DIR / "pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnTrainControlPause.setIcon(icon1)
        self.btnTrainControlPause.setIconSize(QtCore.QSize(32, 32))
        self.btnTrainControlPause.setFlat(True)
        self.btnTrainControlPause.setObjectName("btnTrainControlPause")
        self.layoutTrainControls.addWidget(self.btnTrainControlPause)
        self.btnTrainControlStop = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnTrainControlStop.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(str(IMAGE_DIR / "stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnTrainControlStop.setIcon(icon2)
        self.btnTrainControlStop.setIconSize(QtCore.QSize(40, 40))
        self.btnTrainControlStop.setFlat(True)
        self.btnTrainControlStop.setObjectName("btnTrainControlStop")
        self.layoutTrainControls.addWidget(self.btnTrainControlStop)
        self.lblProgressTotalTitle = QtWidgets.QLabel(self.frameTrain)
        self.lblProgressTotalTitle.setGeometry(QtCore.QRect(350, 520, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblProgressTotalTitle.setFont(font)
        self.lblProgressTotalTitle.setObjectName("lblProgressTotalTitle")
        self.framePit = QtWidgets.QFrame(FormMainMenu)
        self.framePit.setEnabled(True)
        self.framePit.setGeometry(QtCore.QRect(10, 60, 861, 581))
        self.framePit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePit.setObjectName("framePit")
        self.checkBatchedArena = QtWidgets.QCheckBox(self.framePit)
        self.checkBatchedArena.setGeometry(QtCore.QRect(500, 420, 321, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkBatchedArena.setFont(font)
        self.checkBatchedArena.setChecked(False)
        self.checkBatchedArena.setObjectName("checkBatchedArena")
        self.checkShufflePlayers = QtWidgets.QCheckBox(self.framePit)
        self.checkShufflePlayers.setGeometry(QtCore.QRect(500, 390, 321, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkShufflePlayers.setFont(font)
        self.checkShufflePlayers.setChecked(False)
        self.checkShufflePlayers.setObjectName("checkShufflePlayers")
        self.lblCurrentPitRun = QtWidgets.QLabel(self.framePit)
        self.lblCurrentPitRun.setEnabled(True)
        self.lblCurrentPitRun.setGeometry(QtCore.QRect(386, 10, 400, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblCurrentPitRun.setFont(font)
        self.lblCurrentPitRun.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lblCurrentPitRun.setObjectName("lblCurrentPitRun")
        self.lblProgressTitle = QtWidgets.QLabel(self.framePit)
        self.lblProgressTitle.setGeometry(QtCore.QRect(330, 500, 81, 40))
        self.lblProgressTitle.setObjectName("lblProgressTitle")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.framePit)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 480, 271, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.layoutPitControl = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.layoutPitControl.setContentsMargins(0, 0, 0, 0)
        self.layoutPitControl.setObjectName("layoutPitControl")
        self.btnPitControlStart = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnPitControlStart.setText("")
        self.btnPitControlStart.setIcon(icon)
        self.btnPitControlStart.setIconSize(QtCore.QSize(32, 32))
        self.btnPitControlStart.setFlat(True)
        self.btnPitControlStart.setObjectName("btnPitControlStart")
        self.layoutPitControl.addWidget(self.btnPitControlStart)
        self.btnPitControlPause = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnPitControlPause.setText("")
        self.btnPitControlPause.setIcon(icon1)
        self.btnPitControlPause.setIconSize(QtCore.QSize(32, 32))
        self.btnPitControlPause.setFlat(True)
        self.btnPitControlPause.setObjectName("btnPitControlPause")
        self.layoutPitControl.addWidget(self.btnPitControlPause)
        self.btnPitControlStop = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnPitControlStop.setText("")
        self.btnPitControlStop.setIcon(icon2)
        self.btnPitControlStop.setIconSize(QtCore.QSize(40, 40))
        self.btnPitControlStop.setFlat(True)
        self.btnPitControlStop.setObjectName("btnPitControlStop")
        self.layoutPitControl.addWidget(self.btnPitControlStop)
        self.progressPit = QtWidgets.QProgressBar(self.framePit)
        self.progressPit.setGeometry(QtCore.QRect(430, 510, 381, 23))
        self.progressPit.setProperty("value", 0)
        self.progressPit.setObjectName("progressPit")
        self.checkConsoleVerbose = QtWidgets.QCheckBox(self.framePit)
        self.checkConsoleVerbose.setGeometry(QtCore.QRect(500, 450, 321, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkConsoleVerbose.setFont(font)
        self.checkConsoleVerbose.setChecked(False)
        self.checkConsoleVerbose.setObjectName("checkConsoleVerbose")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.framePit)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 20, 361, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layoutPitStats = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layoutPitStats.setContentsMargins(0, 0, 0, 0)
        self.layoutPitStats.setSpacing(6)
        self.layoutPitStats.setObjectName("layoutPitStats")
        self.lblPitStatsTitle = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblPitStatsTitle.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblPitStatsTitle.setFont(font)
        self.lblPitStatsTitle.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lblPitStatsTitle.setObjectName("lblPitStatsTitle")
        self.layoutPitStats.addWidget(self.lblPitStatsTitle)
        self.lblPitStatus = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lblPitStatus.setFont(font)
        self.lblPitStatus.setObjectName("lblPitStatus")
        self.layoutPitStats.addWidget(self.lblPitStatus)
        self.lblPitNumGames = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblPitNumGames.setFont(font)
        self.lblPitNumGames.setObjectName("lblPitNumGames")
        self.layoutPitStats.addWidget(self.lblPitNumGames)
        self.lblPitWinrates = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblPitWinrates.setFont(font)
        self.lblPitWinrates.setObjectName("lblPitWinrates")
        self.layoutPitStats.addWidget(self.lblPitWinrates)
        self.lblPitEpsTime = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblPitEpsTime.setFont(font)
        self.lblPitEpsTime.setObjectName("lblPitEpsTime")
        self.layoutPitStats.addWidget(self.lblPitEpsTime)
        self.lblPitIterTime = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblPitIterTime.setFont(font)
        self.lblPitIterTime.setObjectName("lblPitIterTime")
        self.layoutPitStats.addWidget(self.lblPitIterTime)
        self.lblPitTimeRemaining = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblPitTimeRemaining.setFont(font)
        self.lblPitTimeRemaining.setObjectName("lblPitTimeRemaining")
        self.layoutPitStats.addWidget(self.lblPitTimeRemaining)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.framePit)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(500, 80, 169, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layoutPitButtons = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layoutPitButtons.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.layoutPitButtons.setContentsMargins(0, 0, 0, 0)
        self.layoutPitButtons.setSpacing(6)
        self.layoutPitButtons.setObjectName("layoutPitButtons")
        self.btnLoadPitArgs = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnLoadPitArgs.setMinimumSize(QtCore.QSize(0, 50))
        self.btnLoadPitArgs.setAutoDefault(False)
        self.btnLoadPitArgs.setFlat(False)
        self.btnLoadPitArgs.setObjectName("btnLoadPitArgs")
        self.layoutPitButtons.addWidget(self.btnLoadPitArgs)
        self.btnLoadPitEnv = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnLoadPitEnv.setMinimumSize(QtCore.QSize(0, 50))
        self.btnLoadPitEnv.setObjectName("btnLoadPitEnv")
        self.layoutPitButtons.addWidget(self.btnLoadPitEnv)
        self.btnEditPlayers = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnEditPlayers.setMinimumSize(QtCore.QSize(0, 50))
        self.btnEditPlayers.setObjectName("btnEditPlayers")
        self.layoutPitButtons.addWidget(self.btnEditPlayers)
        self.btnEditPitArgs = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnEditPitArgs.setMinimumSize(QtCore.QSize(0, 50))
        self.btnEditPitArgs.setObjectName("btnEditPitArgs")
        self.layoutPitButtons.addWidget(self.btnEditPitArgs)
        self.btnRemoveArgsPit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnRemoveArgsPit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnRemoveArgsPit.setFont(font)
        self.btnRemoveArgsPit.setObjectName("btnRemoveArgsPit")
        self.layoutPitButtons.addWidget(self.btnRemoveArgsPit)
        self.btnTabTrain = QtWidgets.QPushButton(FormMainMenu)
        self.btnTabTrain.setGeometry(QtCore.QRect(10, 10, 81, 41))
        self.btnTabTrain.setCheckable(True)
        self.btnTabTrain.setChecked(True)
        self.btnTabTrain.setObjectName("btnTabTrain")
        self.btnTabPit = QtWidgets.QPushButton(FormMainMenu)
        self.btnTabPit.setGeometry(QtCore.QRect(100, 10, 81, 41))
        self.btnTabPit.setCheckable(True)
        self.btnTabPit.setChecked(False)
        self.btnTabPit.setObjectName("btnTabPit")

        self.retranslateUi(FormMainMenu)
        QtCore.QMetaObject.connectSlotsByName(FormMainMenu)

    def retranslateUi(self, FormMainMenu):
        _translate = QtCore.QCoreApplication.translate
        FormMainMenu.setWindowTitle(_translate("FormMainMenu", "AlphaZero GUI"))
        self.lblCurrentRun.setText(_translate("FormMainMenu", "<html><head/><body><p>Current Run:</p><p>None</p></body></html>"))
        self.lblTrainStatsTitle.setText(_translate("FormMainMenu", "Training Stats"))
        self.lblStatus.setText(_translate("FormMainMenu", "Status: "))
        self.lblTrainIteration.setText(_translate("FormMainMenu", "Iteration: "))
        self.lblTrainSelfPlayIter.setText(_translate("FormMainMenu", "Self Play Iter: "))
        self.lblTrainNumGames.setText(_translate("FormMainMenu", "Games played: "))
        self.lblTrainLossPolicy.setText(_translate("FormMainMenu", "Policy Loss: "))
        self.lblTrainLossValue.setText(_translate("FormMainMenu", "Value Loss: "))
        self.lblTrainLossTotal.setText(_translate("FormMainMenu", "Total Loss: "))
        self.lblTrainEpsTime.setText(_translate("FormMainMenu", "Episode Time: "))
        self.lblTrainIterTime.setText(_translate("FormMainMenu", "Iteration Time: "))
        self.lblTrainTimeRemaining.setText(_translate("FormMainMenu", "Est. Time Remaining: "))
        self.lblProgressIterTitle.setText(_translate("FormMainMenu", "Iteration:"))
        self.btnLoadTrainArgs.setText(_translate("FormMainMenu", "Load Train Args"))
        self.btnEditTrainArgs.setText(_translate("FormMainMenu", "Edit Args"))
        self.btnLoadTrainEnv.setText(_translate("FormMainMenu", "Load Env"))
        self.btnOpenTensorboard.setText(_translate("FormMainMenu", "Tensorboard"))
        self.btnRemoveArgs.setText(_translate("FormMainMenu", "Remove Saved Args"))
        self.lblProgressTotalTitle.setText(_translate("FormMainMenu", "Total:"))
        self.checkBatchedArena.setText(_translate("FormMainMenu", "Batched games (for many games, no visual)"))
        self.checkShufflePlayers.setText(_translate("FormMainMenu", "Shuffle players"))
        self.lblCurrentPitRun.setText(_translate("FormMainMenu", "<html><head/><body><p>Current Run:</p><p>None</p></body></html>"))
        self.lblProgressTitle.setText(_translate("FormMainMenu", "Progress:"))
        self.checkConsoleVerbose.setText(_translate("FormMainMenu", "Verbose in console (for debug)"))
        self.lblPitStatsTitle.setText(_translate("FormMainMenu", "Arena Stats"))
        self.lblPitStatus.setText(_translate("FormMainMenu", "Status: "))
        self.lblPitNumGames.setText(_translate("FormMainMenu", "Games played:"))
        self.lblPitWinrates.setText(_translate("FormMainMenu", "Win Rates:"))
        self.lblPitEpsTime.setText(_translate("FormMainMenu", "Episode Time: "))
        self.lblPitIterTime.setText(_translate("FormMainMenu", "Total Time: "))
        self.lblPitTimeRemaining.setText(_translate("FormMainMenu", "Est. Time Remaining: "))
        self.btnLoadPitArgs.setText(_translate("FormMainMenu", "Load Arena Args"))
        self.btnEditPitArgs.setText(_translate("FormMainMenu", "Edit Args"))
        self.btnLoadPitEnv.setText(_translate("FormMainMenu", "Load Env"))
        self.btnEditPlayers.setText(_translate("FormMainMenu", "Edit Players"))
        self.btnRemoveArgsPit.setText(_translate("FormMainMenu", "Remove Saved Args"))
        self.btnTabTrain.setText(_translate("FormMainMenu", "Train"))
        self.btnTabPit.setText(_translate("FormMainMenu", "Arena"))


class Ui_DialogCombo(QtWidgets.QDialog):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)

    def setupUi(self, DialogCombo):
        DialogCombo.setObjectName("DialogCombo")
        DialogCombo.resize(340, 149)
        self.comboBox = QtWidgets.QComboBox(DialogCombo)
        self.comboBox.setGeometry(QtCore.QRect(10, 80, 321, 28))
        self.comboBox.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.lblTitle = QtWidgets.QLabel(DialogCombo)
        self.lblTitle.setGeometry(QtCore.QRect(9, 9, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.btnBox = QtWidgets.QDialogButtonBox(DialogCombo)
        self.btnBox.setGeometry(QtCore.QRect(180, 120, 156, 23))
        self.btnBox.setOrientation(QtCore.Qt.Horizontal)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnBox.setObjectName("btnBox")

        self.retranslateUi(DialogCombo)
        QtCore.QMetaObject.connectSlotsByName(DialogCombo)

    def retranslateUi(self, DialogCombo):
        _translate = QtCore.QCoreApplication.translate
        DialogCombo.setWindowTitle(_translate("DialogCombo", "Combo Dialog"))
        self.lblTitle.setText(_translate("DialogCombo", "Title Text"))
